### ISSUE TITLE
"0 Games were renamed" using DAT file

### ISSUE THREAD

**Issue by EmpirixDz** [gerrykeys/playnite-mame-utility#3]
Tried to use this on 3 ROMs using a DAT file that I got from here: https://github.com/libretro/FBNeo/tree/master/dats/
but it returns "0 Games were renamed".
Using the same DAT and ROMs to do a manual scan in retroarch resulted in the games having the right names in RA, so I don't think the problem is caused by the roms/dat
![v70BcF6s7R](https://user-images.githubusercontent.com/7285523/139865514-a931518f-1939-40d4-b499-abb063a3629c.jpg)
.

**Comment by gerrykeys** [comment]
Hi,

have you set "FBNeo" in Extension settings?

**Comment by EmpirixDz** [comment]
I just figured that out after I posted this, it's working as intended right now. Sorry for bothering you.

**Comment by gerrykeys** [comment]
do not worry! Have fun with the extension
