### ISSUE TITLE
Feature Request: Set icons of selected games

### ISSUE THREAD

**Issue by epeternally** [gerrykeys/playnite-mame-utility#6]
Not having to manually assign cover and background art is great, but if you're running Playnite in details view that still leaves an ugly default icon. [Progetto-Snaps](https://www.progettosnaps.net/icons/) has a set of icons matching the standard MAME naming convention, would it be possible to automate importing them into Playnite?

**Comment by gerrykeys** [comment]
Hello, first of all thank you very much for the support and the donation you made.
Thanks for using my plugin. 
I understood the request and i will add this feature as soon as possible: I think I can release a new version within 10 days.
Stay Tuned!

**Comment by gerrykeys** [comment]
Hi @epeternally ,

i just released new version of the plugin (v1.0.4) which contains your feature request.
Let me know if everything works.
