### ISSUE TITLE
Renaming errors from FBNEO xml/dat

### ISSUE THREAD

**Issue by OldFinbar** [gerrykeys/playnite-mame-utility#8]
When renaming FBNEO games that have a "comment" line before the "description" line in the xml/dat file, it seems the name is being taken from the "comment" line instead of the "description" line.

This results in a lot of games being renamed "bootleg" or "bad sound" instead of the game name. I tested this by removing all "comment" lines from the xml and this fixed the issue.

Also, if the "machine name" line contains "sampleof=[rom name]" , the game will not be renamed at all. I removed all cases of "sampleof=[rom name]" and this fixed the issue as well. 

Hopefully this is helpful. It's not a big problem to use Notepad++ to get around this issue, but I thought I'd best report it. Thank you for this great plugin!

**Comment by gerrykeys** [comment]
Thanks for report this issue.
I will work on a fix.

**Comment by elazar55** [comment]
I'm wondering if the following will fix the issue.

https://github.com/gerrykeys/playnite-mame-utility/blob/284cda45d2ab3e4d2f232675611428321372aec8/src/Services/Engine/Platforms/FBNeo/private/FBNeoMachinesParser.cs#L39

Can you change this line to
`if (machineXmlNode.FirstChild != null) machine.description = machineXmlNode.Attributes["description"].Value;`

**Comment by gerrykeys** [comment]
Sorry about the late answer: i'm very busy in this period.
Il will try soon to fix the problem and i will come back here.
Thanks

**Comment by gerrykeys** [comment]
I solved in the 1.0.5 version.
Sorry again for the late support.
