### ISSUE TITLE
Feature Request: Use MAME metadata.

### ISSUE THREAD

**Issue by TheT113** [gerrykeys/playnite-mame-utility#9]
Since this hasn't been requested before, despite what a huge feature it would be, I'm worried this will fall on deaf ears, but.

Tagging all the MAME games, especially the non-Arcade games, and filtering them is absurdly difficult. But all the data already exists in MAME, just waiting to be used.

From the MAME datafiles, moving Genre or Category to Genre, Year to Release, Manufacturer to Developer/Publisher. Adding tags for driver status (Good/Imperfect/Preliminary).

And then, ideally, using the parent/clone list to merge all clones into a parent and name their Installation to match the (long version) Game Title.

So many of the non-Arcade games in MAME, the Computers and Handheld games and Plug and Play games, are not well documented anywhere except in MAME's database. This would be an ideal starting point for adding them into the database, and then it would be on the user's end to manually change them to the desired "Platform", hide Preliminary games, etc. But without the tags being present to batch sort them, it would take years to process all the data manually.

**Comment by gerrykeys** [comment]
Some of the things you said can be implemented.
I will take it into consideration.
Thanks
